### ISSUE TITLE
Language Model Training -- invalid  shape

### ISSUE THREAD

**Issue by joklaff** [zalandoresearch/flair#916] opened 2019-07-20 17:12 UTC
**Describe the bug**
I am trying to continue the training of the `news-forward` language model on domain specific data, which works in a jupyter notebook but fails when executing the code in a plain python script.   
The error message is the following:
```
Traceback (most recent call last):
  File "flair-fine-tuning.py", line 35, in <module>
    checkpoint=True)
  File "/home/jonas/.pyenv/versions/3.7.2/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py", line 358, in train
    loss = self.loss_function(output.view(-1, ntokens), targets)
RuntimeError: shape '[-1, 275]' is invalid for input of size 630000
```
I prepared the corpus as stated in [part 9 of the tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md).  
The notebook server runs from the main directory and both the notebook as well as the script are in the same level:
```
corpus
- test.txt
- train
-- train_split_*
- valid.txt
jupyter_notebook_train.ipynb
plain_python_train.py
```
When I run the following  code in the jupyter notebook the training runs as expected but if I try to run it in a plain python script I get the abovementioned error.
**To Reproduce**
To reproduce the error try to run the following script with:
`python 3.7.2` `flair==0.4.2` `torch==1.1.0`  

 Executed code:
```
from flair.data import Dictionary
from flair.embeddings import FlairEmbeddings
from flair.trainers.language_model_trainer import LanguageModelTrainer, TextCorpus
from pathlib import Path


# are you training a forward or backward LM?
is_forward_lm = True

# load the default character dictionary
dictionary: Dictionary = Dictionary.load('chars')

# get your corpus, process forward and at the character level
corpus = TextCorpus(Path('./corpus'),
                    dictionary,
                    is_forward_lm,
                    character_level=True)

# instantiate an existing LM, such as one from the FlairEmbeddings
language_model = FlairEmbeddings('news-forward').lm

# use the model trainer to fine-tune this model on your corpus
trainer = LanguageModelTrainer(language_model, corpus)

trainer.train(Path('resources/taggers/language_model'),
              sequence_length=100,
              mini_batch_size=100,
              max_epochs=50,
              learning_rate=20,
              anneal_factor=0.4,
              patience=10,
              checkpoint=True)

```
**Environment (please complete the following information):**

_Local Machine_:
 - OS [e.g. iOS, Linux]:  Manjaro Linux 18.0.4 Illyria
 - Version [e.g. flair-0.3.2]: `python 3.7.2` `flair==0.4.2` `torch==1.1.0`  

_Additional Machine_:
- OS: `Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)`
- Versions: `python 3.7.2` `flair==0.4.2` `torch==1.1.0`  

**Additional context**
I hope I included all the necessary information and really much looking forward to any advice to solve this problem since I srsly have no clue what happened.

I also tested the behavior on the above stated additional machine and the message is exactly the same. 

If i missed any information please let me know....I think i probably just make a silly mistake but haven't spotted it  so far... 
Thanks so many in advance!

**Comment by alanakbik** [comment] 2019-07-22 10:09
Hi @joklaff thanks for sharing the code snippet - I think the problem is that there is a mismatch in the character dictionary between the model you load and the model you train. I.e. the model you load in the line 

```python
language_model = FlairEmbeddings('news-forward').lm
```

may have been trained with a different Dictionary than the one you get with 

```python
dictionary: Dictionary = Dictionary.load('chars')
```

To fix this, you could make sure to use the same dictionary of the existing language model. You would need to change your code like this: 

```python
from flair.data import Dictionary
from flair.embeddings import FlairEmbeddings
from flair.trainers.language_model_trainer import LanguageModelTrainer, TextCorpus


# are you training a forward or backward LM?
is_forward_lm = True

# instantiate an existing LM, such as one from the FlairEmbeddings
language_model = FlairEmbeddings('news-forward').lm

# get the dictionary from the existing language model
dictionary: Dictionary = language_model.dictionary

# get your corpus, process forward and at the character level
corpus = TextCorpus('./corpus',
                    dictionary,
                    is_forward_lm,
                    character_level=True)

# use the model trainer to fine-tune this model on your corpus
trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/language_model',
              sequence_length=100,
              mini_batch_size=100,
              max_epochs=50,
              learning_rate=20,
              anneal_factor=0.4,
              patience=10,
              checkpoint=True)
```

I'll correct this in the tutorial as well!

**Comment by alanakbik** [comment] 2019-07-22 16:13
Closing for now, please feel free to reopen if there are any more questions!

**Closed by alanakbik** 2019-07-22 16:13 UTC
Labels: bug

**Comment by joklaff** [comment] 2019-07-22 19:24
Thank you very much for the super quick reply!
Your solution solved the problem for me :+1:
