### ISSUE TITLE
Preserve multiline text structure

### ISSUE THREAD

**Issue by muchas** [zalandoresearch/flair#737] opened 2019-05-18 11:50 UTC
Hi, I'm training NER model with custom corpus where single example is a paragraph of text (FB post). I'm using `Sentence(text, use_tokenizer=True)` for tokenization / corpus creation purposes however this method removes line breaks which are important information about post structure in terms of ner tags prediction.

Is there a quick way to preserve line breaks information or should I replace tokenizer entirely?

**Comment by alanakbik** [comment] 2019-05-23 11:38
Hello @muchas please excuse the belated reply. Unfortunately the current implementation of the in-built tokenizer does indeed remove line breaks. The best workaround presently positible is to first use an external tokenizer to tokenize your text the way you want it and then call the `Sentence` object with `use_tokenizer=False`, i.e.

```python
from flair.data import Sentence

# original text
text = 'Re: Hello \n\nHello back.'
print(text)

# sentence object with tokenizer unfortunately removes newlines
sentence = Sentence(text, use_tokenizer=True)
print(sentence)

# use external tokenizer to produce a string like this instead:
whitespace_tokenized_text = 'Re : Hello \n \n Hello back .'

# then make a sentence object without tokenizer
sentence = Sentence(whitespace_tokenized_text, use_tokenizer=False)

# whitespaces are preserved
print(sentence)
```

This would work for now. In the near future, we want to add support for different tokenizers (see #563), so such workaround should not be needed anymore. Hope this helps!

**Comment by muchas** [comment] 2019-05-26 07:37
This workaround should help, thanks!

**Comment by alanakbik** [comment] 2019-05-27 15:56
Great! Closing the issue, but feel free to reopen if you have more questions!

**Closed by alanakbik** 2019-05-27 15:56 UTC
Labels: question

**Comment by alejandrojcastaneira** [comment] 2019-07-28 16:53
Hello, On the train NER-Tagger format each example should be separate by a newline, how I could Include newlines tokens in examples , without been taken as a sentences separators?

**Comment by alanakbik** [comment] 2019-07-31 10:57
@alejandrojcastaneira I am not if the column format was designed to deal with newlines. One potential workaround I could think of would be to create a special character for newlines and replace all newlines in your data with this special character. Maybe that could address your use case?

**Comment by alejandrojcastaneira** [comment] 2019-07-31 11:57
Thank you for your quick reply, that's exactly what I am doing at the moment, although I'm not sure if handling newlines out-of-the-box will have a big impact at pretraining languages models and doing entity recognition over long texts.

**Comment by jonasadigi** [comment] 2021-03-25 15:58
Hi, this workaround feels a bit awkward, because with it you must always make sure that newlines get replaced with that character (for finetuning the LMs, NER-Training, Production). I think it would be great if `ColumnDataset` supported newlines and would let the user define what constitutes a new example. Since Flair now [supports newline Tokens](https://github.com/flairNLP/flair/commit/de1d6fb10a9288b338aab4d265e6f00470be6287#diff-16f24899e2f13974846de554a7cd57d19e36d0261a637d3783a2ec6a84969e97) I think this also would be more consistent. Please consider adding this feature.
