### ISSUE TITLE
Model.train not responding

### ISSUE THREAD

**Issue by pdsing** [zalandoresearch/flair#517] opened 2019-02-19 09:59 UTC
I am trying to create a model to classify Amazon reviews. I have a set of ~10,000 reviews and ratings from Amazon. I would like to do the following:

1. Use the review text
2. Label the rating (1 - 5)
3. Train the TextClassifier model
4. Predict the rating based on the review text

I am using Google colab with 12 GB RAM.

I tried using the following document embeddings:
1. document_embeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_size=512, reproject_words=True, reproject_words_dimension=256)
2. document_embeddings = DocumentPoolEmbeddings(word_embeddings)

But while training the model I get no response. The machine is stuck with the message -

2019-02-19 09:17:32,953 ----------------------------------------------------------------------------------------------------
2019-02-19 09:17:32,955 Evaluation method: MICRO_F1_SCORE
2019-02-19 09:17:32,959 ----------------------------------------------------------------------------------------------------
2019-02-19 09:18:30,393 epoch 1 - iter 0/249 - loss 0.05150341

There is no progress in any iteration/ epoch. The RAM is maxed out and Google Colab shuts the runtime.

Data and ipython notebooks (after zipping are attached.

https://github.com/zalandoresearch/flair/files/2879415/Amazon_review_analysis_flair.zip
https://github.com/zalandoresearch/flair/files/2879410/BVR_analysis_data.zip

Any help would be appreciated.

**Comment by gccome** [comment] 2019-02-19 15:56
Hi @pdsing to me this is out of memory issue. I ran into this issue a lot when I was training NER model with Flair. Seems like Flair doesn't throw error message for it.

**Comment by alanakbik** [comment] 2019-02-19 16:34
Hello @pdsing yes this could be an out of memory issue. Which word embeddings are you using? 

Also, which version of flair are you using?

**Comment by pdsing** [comment] 2019-02-19 17:37
@gccome @alanakbik It may be a memory issue, though I am not too sure. The training is stuck on Epoch 1 and iteration 0.

I am using the following Encodings:

word_embeddings = [WordEmbeddings('glove'), 
FlairEmbeddings('news-forward-fast'), FlairEmbeddings('news-backward-fast')]



document_embeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_size=128, reproject_words=True)
classifier = TextClassifier(document_embeddings, label_dictionary=corpus.make_label_dictionary(), multi_label=False)

trainer = ModelTrainer(classifier, corpus)

When I call the trainer.train, the model is stuck on Epoch 1 and iteration 0.

I had attached the full code in my previous comment.

**Comment by alanakbik** [comment] 2019-02-19 17:47
Ah yes, I am seeing some very long sentences in this data set so this could be causing the error. Just to verify, could you run the script with the following word embeddings instead: 

```python
word_embeddings = [WordEmbeddings('glove')]
```
If this works, then its probably an oom error caused by FlairEmbeddings over long sentences (#442).

**Comment by pdsing** [comment] 2019-02-19 17:57
@alanakbik Yes. That seems to resolve the problem. The model is getting trained. But if I do not use the FlairEmbeddings, I would be restricting myself to the vector size of Glove. Secondary research seems to suggest that Google Universal Sentence Encoder (512 size) outperforms Glove.
Would BERT work in this case?

Any suggestions?

**Comment by alanakbik** [comment] 2019-02-19 18:04
Ok that is good - we have in fact added a fix for the issue of the `FlairEmbeddings`, which is already pushed to the current master branch. So if you install from the current master instead of pip you could already use it. 

Then, you can define a maximum window for forward propagation that should address the memory issues, like this: 

```python
word_embeddings = [
    WordEmbeddings('glove'),
    FlairEmbeddings('news-forward-fast', chars_per_chunk=128),
    FlairEmbeddings('news-backward-fast', chars_per_chunk=128),
]
``` 

Version 0.4.1 which will be released soon will also contain this fix.

**Comment by pdsing** [comment] 2019-02-19 18:42
With just the Glove word embedding, the model performance is no good. I tried with 10 Epochs and the model is unable to predict anything! It just gives one of the labels (in my case label 5) as the predicted class.

While training, I get the following stats -

2019-02-19 18:37:07,426 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:07,427 Evaluation method: MICRO_F1_SCORE
2019-02-19 18:37:07,429 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:07,467 epoch 1 - iter 0/249 - loss 0.04735912
2019-02-19 18:37:07,940 epoch 1 - iter 24/249 - loss 0.03604057
2019-02-19 18:37:08,395 epoch 1 - iter 48/249 - loss 0.03492595
2019-02-19 18:37:08,836 epoch 1 - iter 72/249 - loss 0.03469888
2019-02-19 18:37:09,281 epoch 1 - iter 96/249 - loss 0.03487498
2019-02-19 18:37:09,712 epoch 1 - iter 120/249 - loss 0.03508015
2019-02-19 18:37:10,154 epoch 1 - iter 144/249 - loss 0.03523424
2019-02-19 18:37:10,587 epoch 1 - iter 168/249 - loss 0.03509101
2019-02-19 18:37:11,046 epoch 1 - iter 192/249 - loss 0.03503463
2019-02-19 18:37:11,518 epoch 1 - iter 216/249 - loss 0.03490432
2019-02-19 18:37:11,947 epoch 1 - iter 240/249 - loss 0.03491753
2019-02-19 18:37:12,096 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:12,097 EPOCH 1 done: loss 0.0350 - lr 0.1000 - bad epochs 0
2019-02-19 18:37:12,571 DEV  : loss 0.03877527 - f-score 0.5586 - acc 0.5586
2019-02-19 18:37:13,162 TEST : loss 0.04066545 - f-score 0.5521 - acc 0.5521
2019-02-19 18:37:17,029 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:17,062 epoch 2 - iter 0/249 - loss 0.03714928
2019-02-19 18:37:17,510 epoch 2 - iter 24/249 - loss 0.03555125
2019-02-19 18:37:17,996 epoch 2 - iter 48/249 - loss 0.03493485
2019-02-19 18:37:18,435 epoch 2 - iter 72/249 - loss 0.03472124
2019-02-19 18:37:18,893 epoch 2 - iter 96/249 - loss 0.03465451
2019-02-19 18:37:19,329 epoch 2 - iter 120/249 - loss 0.03426290
2019-02-19 18:37:19,741 epoch 2 - iter 144/249 - loss 0.03437382
2019-02-19 18:37:20,212 epoch 2 - iter 168/249 - loss 0.03426556
2019-02-19 18:37:20,665 epoch 2 - iter 192/249 - loss 0.03416871
2019-02-19 18:37:21,154 epoch 2 - iter 216/249 - loss 0.03410254
2019-02-19 18:37:21,599 epoch 2 - iter 240/249 - loss 0.03403004
2019-02-19 18:37:21,739 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:21,741 EPOCH 2 done: loss 0.0341 - lr 0.1000 - bad epochs 0
2019-02-19 18:37:22,219 DEV  : loss 0.03647462 - f-score 0.5686 - acc 0.5686
2019-02-19 18:37:22,815 TEST : loss 0.03719761 - f-score 0.5611 - acc 0.5611
2019-02-19 18:37:26,776 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:26,809 epoch 3 - iter 0/249 - loss 0.03375318
2019-02-19 18:37:27,253 epoch 3 - iter 24/249 - loss 0.03536943
2019-02-19 18:37:27,714 epoch 3 - iter 48/249 - loss 0.03421587
2019-02-19 18:37:28,169 epoch 3 - iter 72/249 - loss 0.03415778
2019-02-19 18:37:28,610 epoch 3 - iter 96/249 - loss 0.03370122
2019-02-19 18:37:29,111 epoch 3 - iter 120/249 - loss 0.03374776
2019-02-19 18:37:29,576 epoch 3 - iter 144/249 - loss 0.03364827
2019-02-19 18:37:30,057 epoch 3 - iter 168/249 - loss 0.03380115
2019-02-19 18:37:30,536 epoch 3 - iter 192/249 - loss 0.03380862
2019-02-19 18:37:30,967 epoch 3 - iter 216/249 - loss 0.03358849
2019-02-19 18:37:31,419 epoch 3 - iter 240/249 - loss 0.03346876
2019-02-19 18:37:31,562 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:31,563 EPOCH 3 done: loss 0.0336 - lr 0.1000 - bad epochs 0
2019-02-19 18:37:32,066 DEV  : loss 0.03701325 - f-score 0.6006 - acc 0.6006
2019-02-19 18:37:32,673 TEST : loss 0.03878200 - f-score 0.5952 - acc 0.5952
2019-02-19 18:37:36,526 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:36,569 epoch 4 - iter 0/249 - loss 0.03212275
2019-02-19 18:37:37,074 epoch 4 - iter 24/249 - loss 0.03347648
2019-02-19 18:37:37,583 epoch 4 - iter 48/249 - loss 0.03373414
2019-02-19 18:37:38,069 epoch 4 - iter 72/249 - loss 0.03352746
2019-02-19 18:37:38,533 epoch 4 - iter 96/249 - loss 0.03349809
2019-02-19 18:37:38,964 epoch 4 - iter 120/249 - loss 0.03308356
2019-02-19 18:37:39,429 epoch 4 - iter 144/249 - loss 0.03312004
2019-02-19 18:37:39,899 epoch 4 - iter 168/249 - loss 0.03316231
2019-02-19 18:37:40,360 epoch 4 - iter 192/249 - loss 0.03304311
2019-02-19 18:37:40,805 epoch 4 - iter 216/249 - loss 0.03300589
2019-02-19 18:37:41,274 epoch 4 - iter 240/249 - loss 0.03309760
2019-02-19 18:37:41,410 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:41,411 EPOCH 4 done: loss 0.0332 - lr 0.1000 - bad epochs 0
2019-02-19 18:37:41,899 DEV  : loss 0.03741231 - f-score 0.5766 - acc 0.5766
2019-02-19 18:37:42,505 TEST : loss 0.03745073 - f-score 0.5661 - acc 0.5661
2019-02-19 18:37:46,335 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:46,372 epoch 5 - iter 0/249 - loss 0.03681587
2019-02-19 18:37:46,845 epoch 5 - iter 24/249 - loss 0.03225585
2019-02-19 18:37:47,347 epoch 5 - iter 48/249 - loss 0.03275592
2019-02-19 18:37:47,793 epoch 5 - iter 72/249 - loss 0.03274086
2019-02-19 18:37:48,279 epoch 5 - iter 96/249 - loss 0.03277621
2019-02-19 18:37:48,716 epoch 5 - iter 120/249 - loss 0.03278429
2019-02-19 18:37:49,197 epoch 5 - iter 144/249 - loss 0.03286910
2019-02-19 18:37:49,650 epoch 5 - iter 168/249 - loss 0.03285377
2019-02-19 18:37:50,104 epoch 5 - iter 192/249 - loss 0.03271413
2019-02-19 18:37:50,563 epoch 5 - iter 216/249 - loss 0.03268025
2019-02-19 18:37:50,960 epoch 5 - iter 240/249 - loss 0.03277687
2019-02-19 18:37:51,114 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:51,115 EPOCH 5 done: loss 0.0328 - lr 0.1000 - bad epochs 0
2019-02-19 18:37:51,595 DEV  : loss 0.03595662 - f-score 0.5776 - acc 0.5776
2019-02-19 18:37:52,189 TEST : loss 0.03619679 - f-score 0.5661 - acc 0.5661
2019-02-19 18:37:56,011 ----------------------------------------------------------------------------------------------------
2019-02-19 18:37:56,048 epoch 6 - iter 0/249 - loss 0.02692021
2019-02-19 18:37:56,509 epoch 6 - iter 24/249 - loss 0.03494235
2019-02-19 18:37:56,951 epoch 6 - iter 48/249 - loss 0.03380025
2019-02-19 18:37:57,396 epoch 6 - iter 72/249 - loss 0.03318965
2019-02-19 18:37:57,812 epoch 6 - iter 96/249 - loss 0.03308012
2019-02-19 18:37:58,270 epoch 6 - iter 120/249 - loss 0.03263205
2019-02-19 18:37:58,727 epoch 6 - iter 144/249 - loss 0.03264292
2019-02-19 18:37:59,209 epoch 6 - iter 168/249 - loss 0.03279029
2019-02-19 18:37:59,669 epoch 6 - iter 192/249 - loss 0.03266464
2019-02-19 18:38:00,106 epoch 6 - iter 216/249 - loss 0.03261115
2019-02-19 18:38:00,588 epoch 6 - iter 240/249 - loss 0.03240487
2019-02-19 18:38:00,732 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:00,733 EPOCH 6 done: loss 0.0326 - lr 0.1000 - bad epochs 0
2019-02-19 18:38:01,215 DEV  : loss 0.03546082 - f-score 0.5866 - acc 0.5866
2019-02-19 18:38:01,816 TEST : loss 0.03582988 - f-score 0.5782 - acc 0.5782
2019-02-19 18:38:05,644 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:05,684 epoch 7 - iter 0/249 - loss 0.03733085
2019-02-19 18:38:06,138 epoch 7 - iter 24/249 - loss 0.03295432
2019-02-19 18:38:06,603 epoch 7 - iter 48/249 - loss 0.03253991
2019-02-19 18:38:07,078 epoch 7 - iter 72/249 - loss 0.03234384
2019-02-19 18:38:07,556 epoch 7 - iter 96/249 - loss 0.03239176
2019-02-19 18:38:08,015 epoch 7 - iter 120/249 - loss 0.03247721
2019-02-19 18:38:08,472 epoch 7 - iter 144/249 - loss 0.03228443
2019-02-19 18:38:08,943 epoch 7 - iter 168/249 - loss 0.03237970
2019-02-19 18:38:09,378 epoch 7 - iter 192/249 - loss 0.03244423
2019-02-19 18:38:09,827 epoch 7 - iter 216/249 - loss 0.03242446
2019-02-19 18:38:10,262 epoch 7 - iter 240/249 - loss 0.03236372
2019-02-19 18:38:10,401 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:10,402 EPOCH 7 done: loss 0.0323 - lr 0.1000 - bad epochs 0
2019-02-19 18:38:10,883 DEV  : loss 0.03622932 - f-score 0.5806 - acc 0.5806
2019-02-19 18:38:11,481 TEST : loss 0.03597467 - f-score 0.5671 - acc 0.5671
2019-02-19 18:38:15,277 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:15,314 epoch 8 - iter 0/249 - loss 0.03420059
2019-02-19 18:38:15,785 epoch 8 - iter 24/249 - loss 0.03247097
2019-02-19 18:38:16,242 epoch 8 - iter 48/249 - loss 0.03199862
2019-02-19 18:38:16,709 epoch 8 - iter 72/249 - loss 0.03227572
2019-02-19 18:38:17,142 epoch 8 - iter 96/249 - loss 0.03207902
2019-02-19 18:38:17,582 epoch 8 - iter 120/249 - loss 0.03187608
2019-02-19 18:38:18,075 epoch 8 - iter 144/249 - loss 0.03212790
2019-02-19 18:38:18,528 epoch 8 - iter 168/249 - loss 0.03207395
2019-02-19 18:38:18,975 epoch 8 - iter 192/249 - loss 0.03203470
2019-02-19 18:38:19,408 epoch 8 - iter 216/249 - loss 0.03194526
2019-02-19 18:38:19,858 epoch 8 - iter 240/249 - loss 0.03212463
2019-02-19 18:38:20,003 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:20,004 EPOCH 8 done: loss 0.0322 - lr 0.1000 - bad epochs 0
2019-02-19 18:38:20,503 DEV  : loss 0.03495253 - f-score 0.5866 - acc 0.5866
2019-02-19 18:38:21,119 TEST : loss 0.03518208 - f-score 0.5762 - acc 0.5762
2019-02-19 18:38:24,901 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:24,938 epoch 9 - iter 0/249 - loss 0.03170179
2019-02-19 18:38:25,399 epoch 9 - iter 24/249 - loss 0.03366887
2019-02-19 18:38:25,898 epoch 9 - iter 48/249 - loss 0.03357830
2019-02-19 18:38:26,393 epoch 9 - iter 72/249 - loss 0.03252354
2019-02-19 18:38:26,856 epoch 9 - iter 96/249 - loss 0.03248761
2019-02-19 18:38:27,324 epoch 9 - iter 120/249 - loss 0.03236969
2019-02-19 18:38:27,791 epoch 9 - iter 144/249 - loss 0.03221951
2019-02-19 18:38:28,254 epoch 9 - iter 168/249 - loss 0.03208611
2019-02-19 18:38:28,702 epoch 9 - iter 192/249 - loss 0.03203939
2019-02-19 18:38:29,143 epoch 9 - iter 216/249 - loss 0.03193117
2019-02-19 18:38:29,580 epoch 9 - iter 240/249 - loss 0.03188909
2019-02-19 18:38:29,732 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:29,734 EPOCH 9 done: loss 0.0320 - lr 0.1000 - bad epochs 0
2019-02-19 18:38:30,220 DEV  : loss 0.03538253 - f-score 0.5846 - acc 0.5846
2019-02-19 18:38:30,817 TEST : loss 0.03569196 - f-score 0.5721 - acc 0.5721
2019-02-19 18:38:34,585 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:34,623 epoch 10 - iter 0/249 - loss 0.02230948
2019-02-19 18:38:35,115 epoch 10 - iter 24/249 - loss 0.03082815
2019-02-19 18:38:35,586 epoch 10 - iter 48/249 - loss 0.03104616
2019-02-19 18:38:36,018 epoch 10 - iter 72/249 - loss 0.03157688
2019-02-19 18:38:36,480 epoch 10 - iter 96/249 - loss 0.03177440
2019-02-19 18:38:36,978 epoch 10 - iter 120/249 - loss 0.03180441
2019-02-19 18:38:37,464 epoch 10 - iter 144/249 - loss 0.03176356
2019-02-19 18:38:37,907 epoch 10 - iter 168/249 - loss 0.03180456
2019-02-19 18:38:38,358 epoch 10 - iter 192/249 - loss 0.03174962
2019-02-19 18:38:38,789 epoch 10 - iter 216/249 - loss 0.03173125
2019-02-19 18:38:39,247 epoch 10 - iter 240/249 - loss 0.03179641
2019-02-19 18:38:39,395 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:39,402 EPOCH 10 done: loss 0.0319 - lr 0.1000 - bad epochs 0
2019-02-19 18:38:39,906 DEV  : loss 0.03540914 - f-score 0.5866 - acc 0.5866
2019-02-19 18:38:40,511 TEST : loss 0.03516933 - f-score 0.5782 - acc 0.5782
2019-02-19 18:38:48,181 ----------------------------------------------------------------------------------------------------
2019-02-19 18:38:48,182 Testing using best model ...
2019-02-19 18:38:49,611 MICRO_AVG: acc 0.5782 - f1-score 0.5782
2019-02-19 18:38:49,613 MARCO_AVG: acc 0.2169 - f1-score 0.3665
2019-02-19 18:38:49,614 1          tp: 22 - fp: 22 - fn: 87 - tn: 22 - precision: 0.5000 - recall: 0.2018 - accuracy: 0.2876 - f1-score: 0.2875
2019-02-19 18:38:49,616 2          tp: 3 - fp: 1 - fn: 89 - tn: 3 - precision: 0.7500 - recall: 0.0326 - accuracy: 0.0625 - f1-score: 0.0625
2019-02-19 18:38:49,617 3          tp: 0 - fp: 0 - fn: 80 - tn: 0 - precision: 0.0000 - recall: 0.0000 - accuracy: 0.0000 - f1-score: 0.0000
2019-02-19 18:38:49,618 4          tp: 0 - fp: 2 - fn: 162 - tn: 0 - precision: 0.0000 - recall: 0.0000 - accuracy: 0.0000 - f1-score: 0.0000
2019-02-19 18:38:49,621 5          tp: 552 - fp: 396 - fn: 3 - tn: 552 - precision: 0.5823 - recall: 0.9946 - accuracy: 0.7345 - f1-score: 0.7345
2019-02-19 18:38:49,624 ----------------------------------------------------------------------------------------------------
{'dev_loss_history': [0.03877527266740799,
  0.03647461533546448,
  0.03701325133442879,
  0.037412311881780624,
  0.035956624895334244,
  0.03546081855893135,
  0.036229316145181656,
  0.03495253250002861,
  0.035382527858018875,
  0.03540914133191109],
 'dev_score_history': [0.5586,
  0.5686,
  0.6006,
  0.5766,
  0.5776,
  0.5866,
  0.5806,
  0.5866,
  0.5846,
  0.5866],
 'test_score': 0.5782,
 'train_loss_history': [0.03501818119316749,
  0.03413329999952514,
  0.033577742172983024,
  0.03321830547403584,
  0.03278145701574634,
  0.03262672269771953,
  0.03234621368165733,
  0.03216802779798466,
  0.031953637692971826,
  0.03191888015775879]}

**Comment by alanakbik** [comment] 2019-04-16 16:43
@pdsing were you able to resolve the issues? The fix was included in version 0.4.1 release. If not, feel free to reopen this issue!

**Closed by alanakbik** 2019-04-16 16:43 UTC

**Comment by pdsing** [comment] 2019-04-16 16:52
@alanakbik I will review this in the next couple of days and get back to you.

**Comment by alanakbik** [comment] 2019-04-16 16:53
Ok great!
