### ISSUE TITLE
RuntimeError: storage has wrong size when loading en-sentiment

### ISSUE THREAD

**Issue by rookie32** [zalandoresearch/flair#351] opened 2019-01-02 17:26 UTC
When trying to load the **en-sentiment model**, I get the error:

RuntimeError: storage has wrong size: expected -1862414276 got 22700

I am able to load other models such as **de-offensive-language** and the **ner** SequenceTagger.

Code:
```
from flair.models import TextClassifier
from flair.data import Sentence
classifier = TextClassifier.load('en-sentiment')
```
Possibly related to issue https://github.com/zalandoresearch/flair/issues/172 ?
But the fix for that was merged back in November? https://github.com/zalandoresearch/flair/pull/194

Have tried deleting and redownloading the model.

Platform: Windows 10, Torch 1.0 (cpu), Python 3.6.4 (Anaconda)

**Comment by alanakbik** [comment] 2019-01-02 19:40
Hi @rookie32 - yes it is the same bug as reported in #194, namely that very large models (over 2GB) cannot be de-serialized in certain windows and mac setups. This is a known issue in the pickle library which is used by pytorch to serialize. 

We currently have a workaround in place in which we make sure that models do not go over 2GB in size, but overlooked this with the en-sentiment model. We will fix this for the next release!

**Comment by alanakbik** [comment] 2019-01-02 19:51
Here also the link to the corresponding [pickle issue](https://bugs.python.org/issue24658).

**Comment by pdsing** [comment] 2019-01-09 09:45
I am facing the same issue on my windows machine (windows 10, 8 GB RAM). Do we have a fix for this issue?

**Comment by alanakbik** [comment] 2019-01-11 17:00
Hi @highway11git thanks very much for this! We'll test it and see if we can directly integrate it. Perhaps we could add a special flag to the model loader to allow users to specify which method they want to use to load a model, with the default being the current one.

**Comment by highway11git** [comment] 2019-01-11 21:06
I've updated the gist:
1. `load_big_file` now uses mmap instead of BytesIO, which makes it _much more memory efficient_
2. `_load_state` now also uses the `load_big_file` function if the user doesn't use cuda

Thanks for testing it, and keep us up to date on any progress.

**Comment by alanakbik** [comment] 2019-01-13 12:10
Cool, thanks! We'll test the solution and let you know!

**Comment by alanakbik** [comment] 2019-01-16 13:13
@highway11git @pdsing @rookie32 I've added the fix proposed by @highway11git into a pull request. 

Since we could not reproduce the error on our setups, could you check if this fixed it for you?

**Closed** 2019-01-17 15:23 UTC
Labels: bug

**Comment by dcavar** [comment] 2020-02-03 14:42
Using the newest Flair and torch on Win 10 I still get this error for (other models worked):
tagger = SequenceTagger.load('frame-fast')
or
tagger = SequenceTagger.load('frame')

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-20-02fe8d2768ba> in <module>
----> 1 tagger = SequenceTagger.load('frame-fast')
      2 
      3 sentence_1 = Sentence('George returned to Berlin to return his hat .')
      4 sentence_2 = Sentence('He had a look at different hats .')
      5 

c:\program files\python37\lib\site-packages\flair\nn.py in load(cls, model)
     84             # see https://github.com/zalandoresearch/flair/issues/351
     85             f = file_utils.load_big_file(str(model_file))
---> 86             state = torch.load(f, map_location=flair.device)
     87 
     88         model = cls._init_model_with_state_dict(state)

c:\program files\python37\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    527             with _open_zipfile_reader(f) as opened_zipfile:
    528                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 529         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    530 
    531 

c:\program files\python37\lib\site-packages\torch\serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    700     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    701     unpickler.persistent_load = persistent_load
--> 702     result = unpickler.load()
    703 
    704     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

c:\program files\python37\lib\pathlib.py in __new__(cls, *args, **kwargs)
   1023         if not self._flavour.is_supported:
   1024             raise NotImplementedError("cannot instantiate %r on your system"
-> 1025                                       % (cls.__name__,))
   1026         self._init()
   1027         return self

NotImplementedError: cannot instantiate 'PosixPath' on your system
